#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
#
Name     : perl-YAML-PP
Version  : 0.036
Release  : 30
URL      : https://cpan.metacpan.org/authors/id/T/TI/TINITA/YAML-PP-0.036.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/T/TI/TINITA/YAML-PP-0.036.tar.gz
Summary  : 'YAML 1.2 Processor'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-YAML-PP-bin = %{version}-%{release}
Requires: perl-YAML-PP-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Sub::Uplevel)
BuildRequires : perl(Test::Warn)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Perl module YAML::PP
YAML::PP is a modular YAML processor for YAML 1.2.
Additionally to loading and dumping it provides a parser and emitter. The
parsing events are compatible to the [YAML Test
Suite](https://github.com/yaml/yaml-test-suite) and other libraries like
[libyaml](https://github.com/yaml/libyaml).

%package bin
Summary: bin components for the perl-YAML-PP package.
Group: Binaries

%description bin
bin components for the perl-YAML-PP package.


%package dev
Summary: dev components for the perl-YAML-PP package.
Group: Development
Requires: perl-YAML-PP-bin = %{version}-%{release}
Provides: perl-YAML-PP-devel = %{version}-%{release}
Requires: perl-YAML-PP = %{version}-%{release}

%description dev
dev components for the perl-YAML-PP package.


%package perl
Summary: perl components for the perl-YAML-PP package.
Group: Default
Requires: perl-YAML-PP = %{version}-%{release}

%description perl
perl components for the perl-YAML-PP package.


%prep
%setup -q -n YAML-PP-0.036
cd %{_builddir}/YAML-PP-0.036
pushd ..
cp -a YAML-PP-0.036 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/yamlpp-events
/usr/bin/yamlpp-highlight
/usr/bin/yamlpp-load
/usr/bin/yamlpp-load-dump
/usr/bin/yamlpp-parse-emit

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/YAML::PP.3
/usr/share/man/man3/YAML::PP::Common.3
/usr/share/man/man3/YAML::PP::Constructor.3
/usr/share/man/man3/YAML::PP::Emitter.3
/usr/share/man/man3/YAML::PP::Grammar.3
/usr/share/man/man3/YAML::PP::Highlight.3
/usr/share/man/man3/YAML::PP::Perl.3
/usr/share/man/man3/YAML::PP::Schema.3
/usr/share/man/man3/YAML::PP::Schema::Binary.3
/usr/share/man/man3/YAML::PP::Schema::Core.3
/usr/share/man/man3/YAML::PP::Schema::Failsafe.3
/usr/share/man/man3/YAML::PP::Schema::Include.3
/usr/share/man/man3/YAML::PP::Schema::JSON.3
/usr/share/man/man3/YAML::PP::Schema::Merge.3
/usr/share/man/man3/YAML::PP::Schema::Perl.3
/usr/share/man/man3/YAML::PP::Schema::Tie::IxHash.3
/usr/share/man/man3/YAML::PP::Schema::YAML1_1.3
/usr/share/man/man3/YAML::PP::Type::MergeKey.3
/usr/share/man/man3/YAML::PP::Writer.3
/usr/share/man/man3/YAML::PP::Writer::File.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
